### ISSUE TITLE
performance data request

### ISSUE THREAD

**Issue by srinathv** [ROCm-Developer-Tools/hip-tests#421]
New to this testing system. 

I want to test the performance (timing) of multiple sized data segments of `hipMemCpyAsync` for different Rocm versions..  I think your testing has something like this.  How?

**Comment by srinathv** [comment]
I see that the memory tests are run for basic types.  stdout can be processed.

**Comment by ppanchad-amd** [comment]
Hi @srinathv, apologies for the lack of response. Do you still need assistance with this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@srinathv Closing ticket due to lack of activity.  Please feel free to re-open ticket if you still need assistance. Thanks!
