### ISSUE TITLE
Is HIT tests gone, and why?

### ISSUE THREAD

**Issue by littlewu2508** [ROCm-Developer-Tools/hip-tests#442]
I noticed that https://github.com/ROCm/HIP/commit/405d029422ba8bb6be5a233d5eebedd2ad2e8bd3 removes the HIT tests.

While https://github.com/ROCm/hip-tests/blob/91ee1399dfda8f5cbfc3718de20a489dad18525b/catch/README.md?plain=1#L4 says hip-tests still uses HIT, despite I don't see any hint `HIT` framework being used in this repo, despite some test sources still has `HIT_START` `HIT_END` in comments.

So, I have two questions:

1. Is HIT framework gone?

2. Are the tests in this repo identical to what in https://github.com/ROCm/HIP/tree/rocm-5.7.1/tests/src ? If not, what's their difference?

**Comment by iassiour** [comment]
Hi @littlewu2508, HIP Tests were using HIT framework in the past but are now rewritten to catch2.

The tests from https://github.com/ROCm/HIP/tree/rocm-5.7.1/tests/src have been ported to this repo and as per the rocm-6.0.0 release they have also been removed from HIP repo https://github.com/ROCm/HIP/tree/rocm-6.0.0/

Any remaining references to HIT_START HIT_END in the comments under hip-tests/catch I think they can be removed. I will create an internal PR for that.

**Comment by ppanchad-amd** [comment]
Hi @littlewu2508, do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by littlewu2508** [comment]
Thank you! It's clear now and I have no further question.
