### ISSUE TITLE
hipStreamPerThread multi-thread test not work 

### ISSUE THREAD

**Issue by kevin-gjm** [ROCm-Developer-Tools/hip-tests#449]
in the test case, after detach the created thread also exited. I think the case can't fully test the function of "hipStreamPerThread".

https://github.com/ROCm/hip-tests/blob/f5deb13ce32126176fdae4ed6b3c38ab792738ef/catch/unit/streamperthread/hipStreamPerThread_MultiThread.cc#L53

pthread_detach man page.
'''
The detached attribute merely determines the behavior of the
       system when the thread terminates; it does not prevent the thread
       from being terminated if the process terminates using [exit(3)](https://www.man7.org/linux/man-pages/man3/exit.3.html) (or
       equivalently, if the main thread returns).
''''

I think this case is mainly to check the new thread not have stream dependence(one thread with hipStreamPerThread exit, not effect other threads). 
what about add a rand sleep in below function (Copy_to_device) to check the dependence? and change detach to join. 

https://github.com/ROCm/hip-tests/blob/f5deb13ce32126176fdae4ed6b3c38ab792738ef/catch/unit/streamperthread/hipStreamPerThread_MultiThread.cc#L24C17-L24C17

**Comment by ppanchad-amd** [comment]
Hi @kevin-gjm, internal ticket has been created to investigate this issue. Thanks!

**Comment by schung-amd** [comment]
Hi @kevin-gjm, the `pthread` documentation is not relevant here as the test uses `std::thread`s. The comments in the test identify the scenario that is being tested and what we're watching for in this test:
```
Scenario : App pushes Async task(s) into hipStreamPerThread and did not wait for it to complete.
Watch out : Incomplete task in hipStreamPerThread should not cause any crash due to thread exit.
```
This test is not meant to cover the full functionality of `hipStreamPerThread`, but only to test this specific scenario. Additional tests covering more of hipStreamPerThread can be found in the parent directory.

**Comment by schung-amd** [comment]
Closing this issue, feel free to reopen or create a new issue if you have further questions about these tests.
