### ISSUE TITLE
Question: Whether the OpenGL related interfaces in ROCM 5.7.x are fully supported

### ISSUE THREAD

**Issue by lilx-dev** [ROCm-Developer-Tools/hip-tests#458]
Hello, I would like to ask about some interfaces of OpenGL in ROCM 5.7.x version, especially the following three interfaces: hipGLGetDevices, hipGraphicsGLRegisterBuffer and hipGraphicsGLRegisterImage, whether to fully support the three interfaces, about the three interfaces, whether have drawbacks.

**Comment by tcgu-amd** [comment]
Hey @liana-123456, thanks for reaching out! Would you be able to provide more context? For example, what use cases are you considering? 

In the meantime, here is detailed documentation for hip OpenGL Interop interfaces https://rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/doxygen/html/group___g_l.html

And this here is the source code for these functions https://github.com/ROCm/clr/blob/rocm-5.7.x/hipamd/src/hip_gl.cpp

Hope these helps! :D

**Comment by tcgu-amd** [comment]
Hey @liana-123456. I found your question [here](https://github.com/ROCm/ROCm/issues/2946). Seems like the question has already been answered. I will be closing this issue then. Thanks!
